# Generated by Django 6.1.1 on 2026-10-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='applying_for',
            field=models.CharField(blank=True, help_text='Program or grade applied for. Becomes a link to a program in the academics module.', max_length=200),
        ),
    ]
